[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.5",
]

[dependency-groups]
dev = [
    "ruff>=0.9.2",
]

# [tools.ruff.format]
# line-length = 100